public class sendEmailTemplate {
    public static void fetchEmailTemplate(){
     
        /*
String TemplateBody = et.Body;
String TemplateSubject = et.Subject; TemplateBody =  TemplateBody.replace('{!Contact.Name}',ConName);
TemplateBody =  TemplateBody.replace('Hello ,','Hello ,<br/>' );
TemplateSubject = TemplateSubject.replace('{!Contact.Name}',ConName);
AttIdsWithName.put('TemplateSubject',TemplateSubject);
AttIdsWithName.put('TemplateData',TemplateBody); */
        
    }
    
}